version: '3'

services:
    node:
        build: 
            context: src               
        command: [ "node", "index.test.js" ]
        networks: 
            - sonar-desafio
        volumes: 
            - ./src:/usr/src/app
            - /usr/src/app/node_modules
        tty: true
        ports: 
            - "3000:3000"
    sonar-scanner:
        build: 
            context: .                
        restart: always
        tty: true
        volumes:             
            - .:/usr/src
        networks: 
            - sonar-desafio

networks: 
    sonar-desafio:
        driver: bridge