name: ci-sonarcloud-nodejs
on:
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      
      - uses: actions/checkout@v2
      - name: Use Node.js 15        
        uses: actions/setup-node@v1
        with:
          node-version: 15       
      - run: dir && cd src           
      - run: npm install
      - run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}